import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import localFont from 'next/font/local';
import "./globals.css";
import { gothicFont, geistSans, geistMono } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gothicFont.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}